formatter: "markdown table" # this is required

header-from: main.tf
footer-from: ""

recursive:
  enabled: true

sections:
  hide: []
  show: [] 

content: |-
  {{ .Requirements }}  
  {{- if .Module.Resources }}
    ## Usage
    Basic usage of this submodule is as follows:
    ```hcl
    module "example" {
      {{"\t"}}source  = "<submodule-path>"
    {{- if .Module.RequiredInputs }}
      {{"\n\t"}}# Required variables
      {{- range .Module.RequiredInputs }}
      {{"\t"}}{{ .Name }}  = {{ .GetValue }}
      {{- end }}
      {{- end }}
    {{- if .Module.OptionalInputs }}
      {{"\n\t"}}# Optional variables
      {{- range .Module.OptionalInputs }}
      {{"\t"}}{{ .Name }} = {{ .GetValue | printf "%s" }}
      {{- end }}
      {{- end }}
    }
    ```
  {{- end }}
  {{ .Resources }}
  
  {{ .Inputs }}
  
  {{ .Outputs }}
  
output:
  file: README.md
  mode: inject
  template: |-
      <!-- BEGIN_AUTOMATED_TF_DOCS_BLOCK -->
      {{ .Content }}
      <!-- END_AUTOMATED_TF_DOCS_BLOCK -->
output-values:
  enabled: false
  from: ""
sort:
  enabled: true
  by: name
settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: true
  html: true
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true